title:              Balu Natarajan
email:              balu1inbox@gmail.com
description:        Mining, Emissions reduction, Technology, Product management and leadership 
author:             Balu Natarajan
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   
github_username:    thasildar
facebook_username:  balu.natarajan.716
instagram_username:  
linkedin_username:  baluexec

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
